//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class ChecksSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ChecksSettings defaultInstance = ((ChecksSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ChecksSettings())));
        
        public static ChecksSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Перевод_обозначений_в_старый_вид {
            get {
                return ((bool)(this["Перевод_обозначений_в_старый_вид"]));
            }
            set {
                this["Перевод_обозначений_в_старый_вид"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Перевод_обозначений_при_загрузке_из_Справочника_сокращения_нормалей {
            get {
                return ((bool)(this["Перевод_обозначений_при_загрузке_из_Справочника_сокращения_нормалей"]));
            }
            set {
                this["Перевод_обозначений_при_загрузке_из_Справочника_сокращения_нормалей"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XML_Сериализация_Справочников {
            get {
                return ((bool)(this["XML_Сериализация_Справочников"]));
            }
            set {
                this["XML_Сериализация_Справочников"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Разрешить_редактирование_загруженых_XML {
            get {
                return ((bool)(this["Разрешить_редактирование_загруженых_XML"]));
            }
            set {
                this["Разрешить_редактирование_загруженых_XML"] = value;
            }
        }
    }
}
