//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class ColorSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ColorSettings defaultInstance = ((ColorSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ColorSettings())));
        
        public static ColorSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#00000000")]
        public global::System.Windows.Media.Color SelectedRowErrorColor {
            get {
                return ((global::System.Windows.Media.Color)(this["SelectedRowErrorColor"]));
            }
            set {
                this["SelectedRowErrorColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#00000000")]
        public global::System.Windows.Media.Color SelectedRowValidColor {
            get {
                return ((global::System.Windows.Media.Color)(this["SelectedRowValidColor"]));
            }
            set {
                this["SelectedRowValidColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#00000000")]
        public global::System.Windows.Media.Color SelectedRowNullableColor {
            get {
                return ((global::System.Windows.Media.Color)(this["SelectedRowNullableColor"]));
            }
            set {
                this["SelectedRowNullableColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#00000000")]
        public global::System.Windows.Media.Color SelectedFieldErrorColor {
            get {
                return ((global::System.Windows.Media.Color)(this["SelectedFieldErrorColor"]));
            }
            set {
                this["SelectedFieldErrorColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#00000000")]
        public global::System.Windows.Media.Color SelectedFieldValidColor {
            get {
                return ((global::System.Windows.Media.Color)(this["SelectedFieldValidColor"]));
            }
            set {
                this["SelectedFieldValidColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#00000000")]
        public global::System.Windows.Media.Color SelectedFieldNullableColor {
            get {
                return ((global::System.Windows.Media.Color)(this["SelectedFieldNullableColor"]));
            }
            set {
                this["SelectedFieldNullableColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#00000000")]
        public global::System.Windows.Media.Color ErrorColor {
            get {
                return ((global::System.Windows.Media.Color)(this["ErrorColor"]));
            }
            set {
                this["ErrorColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#00000000")]
        public global::System.Windows.Media.Color ValidColor {
            get {
                return ((global::System.Windows.Media.Color)(this["ValidColor"]));
            }
            set {
                this["ValidColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#00000000")]
        public global::System.Windows.Media.Color NullableColor {
            get {
                return ((global::System.Windows.Media.Color)(this["NullableColor"]));
            }
            set {
                this["NullableColor"] = value;
            }
        }
    }
}
